apiDefinitions:
  main: openapi/api-docs/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
  plugins:
    - './openapi/api-docs/plugins/all-decorators.js'
  decorators:
    decorators/disallow-paths-for-bank: error
    decorators/change-content-for-bank: error

referenceDocs:
  htmlTemplate: ./openapi/templates/index.html
  # theme:
  #   typography:
  #     heading1:
  #       color: "#2f2f59"
  #     heading2:
  #       color: "#194782"
  generateCodeSamples:
    languages:
      - lang: "curl"
      - lang: "C#"
      - lang: "Java"
      - lang: "JavaScript"
      - lang: "Node.js"
      - lang: "Python"