apiDefinitions:
  main: openapi/api-docs/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./openapi/templates/index.html
  theme:
    colors:
      accent:
        main: "#028c6a"
        light: "#d6d6eb"
        dark: "#014635"
        contrastText: "#80c5b4"
      primary:
        main: "#32329f"
        light: "#80c5b4"
        dark: "#14143f"
        contrastText: "#eaeaf5"
      secondary:
        main: "#f59a44"
        light: "#fce0c6"
        contrastText: "#fbd6b4"
    typography:
      heading1:
        lineHeight: 10px
      fieldName:
        lineHeight: 10px
  generateCodeSamples:
    languages:
      - lang: "curl"
      - lang: "C#"
      - lang: "Java"
      - lang: "JavaScript"
      - lang: "Node.js"
      - lang: "Python"