apiDefinitions:
  main: openapi/api-docs/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./openapi/templates/index.html
  theme:
    colors:
      text:
        primary: "#257bff"
  generateCodeSamples:
    languages:
      - lang: "curl"
      - lang: "C#"
      - lang: "Java"
      - lang: "JavaScript"
      - lang: "Node.js"
      - lang: "Python"