apiDefinitions:
  main: openapi/api-docs/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./openapi/templates/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
    typography:
      heading1:
        lineHeight: 10px
      fieldName:
        lineHeight: 10px
  generateCodeSamples:
    languages:
      - lang: "curl"
      - lang: "C#"
      - lang: "Java"
      - lang: "JavaScript"
      - lang: "Node.js"
      - lang: "Python"