openapi: 3.1.0
info:
  version: 1.0.0
  title: 'title'
  #termsOfService: 'https://example.com/terms/'
  contact:
    email: sales@fispan.com
    url: 'https://fispan.com/contact-us/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'url'
  description: 'desc'
x-tagGroups:
  - name: Authentication
    tags:
      - OAuth Token
  - name: Vendor
    tags:
      - Vendor
tags:
  $ref: './tags.yaml'
servers:
  - url: 'https://dev1.fispan.cloud'
  - url: 'http://localhost'
paths:
  $ref: './paths.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes/security_schemes.yaml'