openapi: 3.0.3
info:
  version: 1.0.0
  title: fispan.com
  #termsOfService: 'https://example.com/terms/'
  contact:
    email: sales@fispan.com
    url: 'https://fispan.com/contact-us/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://fispan.com/wp-content/uploads/2019/09/Screenshot.png'
  description: 
    $ref: './commons/description.md'
x-tagGroups:
  - name: Authentication
    tags:
      - OAuth Token
  - name: Vendor
    tags:
      - Vendor
tags:
  $ref: './tags.yaml'
servers:
  - url: 'https://dev1.fispan.cloud'
  - url: 'http://localhost'
paths:
  $ref: '{{process.env.PATHS_FILE}}''
components:
  securitySchemes:
    $ref: './security_schemes.yaml'